#' Gaussian data Generator
#'
#' @description Generating data with given model = changepoint relative position + means + standard deviation
#' @param n number of data to generate
#' @param changepoints vector of position of the changepoint in (0,1] (last element is always 1).
#' @param means vector of means for the consecutive segments (same length as changepoints)
#' @param sigma a positive number = the standard deviation of the data
#' @return a vector of size n generated by the chosen model
#' @examples
#' dataGenerator(100, c(0.3, 0.6, 1), c(1, 2, 3))
dataGenerator <- function(n, changepoints, means, sigma = 1)
{
 SegLength <- diff(c(0, floor(changepoints*n)))
 vectData <- rep(means, SegLength) + rnorm(n, 0, sigma)
  return(vectData)
}

