# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gfpopTransfert_Gauss <- function(vectData, vectWeight, mygraph, K, a, min, max) {
    .Call(`_gfpop_gfpopTransfert_Gauss`, vectData, vectWeight, mygraph, K, a, min, max)
}

gfpopTransfert_Poisson <- function(vectData, vectWeight, mygraph, K, a, min, max) {
    .Call(`_gfpop_gfpopTransfert_Poisson`, vectData, vectWeight, mygraph, K, a, min, max)
}

gfpopTransfert_Binomial <- function(vectData, vectWeight, mygraph, K, a, min, max) {
    .Call(`_gfpop_gfpopTransfert_Binomial`, vectData, vectWeight, mygraph, K, a, min, max)
}

